### ISSUE TITLE
Gazebo Classic Worlds to Gazebo Harmonic Worlds

### ISSUE THREAD

**Issue by kavikode** [Tiago-Harmonic/tiago_harmonic#10]
I'm trying to understand the most effective way to convert the world's from gazebo classic to gazebo Harmonic

I'd like to automate this process to improve efficiency. Are there any steps to follow, please?

Specifically, I'd like to convert the pick.world and bring it to Gazebo Harmonic.

How were the world files created in this repo?

**Comment by Juancams** [comment]
Hi @kavikode 

There is no such thing as a guide, all I can tell you is to look for all the possible [documentation](https://gazebosim.org/docs/harmonic/tutorials/) and [examples](https://github.com/gazebosim/harmonic_demo), and there you will find some changes. In my profile you can find some migrated amazon worlds.

Anyway, almost all worlds can be used directly, and the most typical problem you will find are the [textures/materials](https://discourse.ros.org/t/migration-support-for-models-with-material-scripts/35652), which for now have to be modified by flat colors or added within your collision/visual model.

Also, if your idea is to add a robot, you will have to add some plugins and make the bridges. As I said, everything is in the [gazebo documentation](https://gazebosim.org/docs/harmonic/migrating_gazebo_classic_ros2_packages/), I encourage you to search and get what you intend to do.

Greetings.

**Comment by Juancams** [comment]
Hello!

I'm going to close this issue, assuming that the question has already been resolved. If not, please reopen the issue.

Regards.
