### ISSUE TITLE
Virtual Camera

### ISSUE THREAD

**Issue by kavikode** [Tiago-Harmonic/tiago_harmonic#11]
Thanks for your continued support!

Is there an example of adding a virtual camera to this model?

**Comment by Juancams** [comment]
Hi,

I recommend you check out this [repository](https://gazebosim.org/docs/harmonic/migrating_gazebo_classic_ros2_packages/) where there are examples for directly adding a camera (or other sensors), and it also explains how to migrate it from the gazebo classic.

Regards.
