### ISSUE TITLE
MoveIt 2 Harmonic

### ISSUE THREAD

**Issue by kavikode** [Tiago-Harmonic/tiago_harmonic#2]
How can we integrate MoveIt 2 by launching RViz2 with this TIAGo simulation in ROS2 Jazzy
with Gazebo Harmonic?

Specifically, we'd like to use the MoveIt Python bindings for the inverse kinematics of the end effector as they are not available on Humble.

Is there a working example, please?

If not, what is the best way to implement?

Thank you!

**Comment by fmrico** [comment]
Hi @kavikode ,

I am sure you can push in that direction for yourself with the (hard) work we have done in this open source repo 😉. To develop that example is not in our inminent plans.

Best
Francisco

**Comment by kavikode** [comment]
thanks for your update. How can we change the humble simulation in MoveIt to Jazzy?
