### ISSUE TITLE
pal_gazebo_worlds repository does not have humble-devel branch

### ISSUE THREAD

**Issue by edgarcamilocamacho** [Tiago-Harmonic/tiago_harmonic#3]
Hello.

While executing `vcs import . < tiago_harmonic/dependencies.repos` I get:

```
...
Cloning into '.'...
=== ./pal_gazebo_worlds (git) ===
Could not checkout ref 'humble-devel': fatal: invalid reference: humble-devel
...
```

From [here](https://github.com/Tiago-Harmonic/tiago_harmonic/blob/main/dependencies.repos#L10-L13) I got the repository URL:

https://github.com/Tiago-Harmonic/br2_gazebo_worlds

That does not have [branches](https://github.com/Tiago-Harmonic/br2_gazebo_worlds/branches) or [tags](https://github.com/Tiago-Harmonic/br2_gazebo_worlds/tags) named like `humble-devel`.

I modified the file to point to `main` and I'm going to check if ir works.

**Comment by kavikode** [comment]
did that work?

**Comment by Juancams** [comment]
Yes, this error has already been fixed. There was an error with the name of the branch of said repository.

I proceed to close the issue, thank you very much
