### ISSUE TITLE
Include pointing to wrong path

### ISSUE THREAD

**Issue by edgarcamilocamacho** [Tiago-Harmonic/tiago_harmonic#5]
After fixing the branch problem exposed in #3 and manually installing dependencies as exposed in #4, the build process started but now I got a moveit related problem when building the package `play_motion2`:

```
...
--- stderr: play_motion2
In file included from /root/tiago_ws/src/play_motion2/play_motion2/src/play_motion2/motion_planner.cpp:17:
/root/tiago_ws/src/play_motion2/play_motion2/include/play_motion2/motion_planner.hpp:25:10: fatal error: moveit/move_group_interface/move_group_interface.h: No such file or directory
   25 | #include "moveit/move_group_interface/move_group_interface.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/play_motion2.dir/build.make:90: CMakeFiles/play_motion2.dir/src/play_motion2/motion_planner.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from /root/tiago_ws/src/play_motion2/play_motion2/src/play_motion2/play_motion2.cpp:18:
/root/tiago_ws/src/play_motion2/play_motion2/include/play_motion2/motion_planner.hpp:25:10: fatal error: moveit/move_group_interface/move_group_interface.h: No such file or directory
   25 | #include "moveit/move_group_interface/move_group_interface.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/play_motion2.dir/build.make:104: CMakeFiles/play_motion2.dir/src/play_motion2/play_motion2.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:165: CMakeFiles/play_motion2.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< play_motion2 [0.19s, exited with code 2]
...
```

I installed ALL moveit like:

``` bash
apt-get install ros-jazzy-moveit ros-jazzy-moveit-*
```

But still get the error, I checked the include folder of ROS and there is not a `moveit` folder:

```
# ls -1 /opt/ros/jazzy/include | grep moveit
moveit_acceleration_filter_parameters
moveit_butterworth_filter_parameters
moveit_core
moveit_hybrid_planning
moveit_kinematics
moveit_msgs
moveit_planners
moveit_py
moveit_ros_benchmarks
moveit_ros_control_interface
moveit_ros_move_group
moveit_ros_occupancy_map_monitor
moveit_ros_perception
moveit_ros_planning
moveit_ros_planning_interface
moveit_ros_robot_interaction
moveit_ros_visualization
moveit_ros_warehouse
moveit_servo
moveit_servo_lib_parameters
moveit_setup_app_plugins
moveit_setup_assistant
moveit_setup_controllers
moveit_setup_core_plugins
moveit_setup_framework
moveit_setup_srdf_plugins
moveit_simple_controller_manager
moveit_visual_tools
stomp_moveit_parameters
```

And when looking for the file, it is in another location:

```
# find /opt/ros/jazzy/include  -name move_group_interface.h
/opt/ros/jazzy/include/moveit_ros_planning_interface/moveit/move_group_interface/move_group_interface.h
```

By now I'm just skipping the package:

```
colcon build --symlink-install --packages-skip play_motion2
```

**Comment by kavikode** [comment]
any other workaround?

**Comment by kavikode** [comment]
it seems that several other packages also rely on play_motion2 so I had to do the following 
colcon build --symlink-install --packages-skip play_motion2 tiago_bringup tiago_robot tiago_gazebo tiago_simulation

Yet, it does not work.

On the YouTube demo, it works perfectly, though.

Any suggestions? Please? @fmrico @Juancams @edgarcamilocamacho Thank you

**Comment by kavikode** [comment]
I made the following changes


  pal_urdf_utils:
    type: git
    url: https://github.com/Tiago-Harmonic/pal_urdf_utils.git
    version: jazzy

**Comment by kavikode** [comment]
Thank you so much! this has been successfully resolved!

**Comment by Juancams** [comment]
> I made the following changes
> 
> pal_urdf_utils: type: git url: https://github.com/Tiago-Harmonic/pal_urdf_utils.git version: jazzy

Yeah, sorry. I was changing the branch names of the packages we forked to jazzy yesterday and I missed that one.

Regarding the problems you had, I checked yesterday and no errors appeared, but I'm glad it worked. You probably needed to install dependencies, so we've modified the steps so that now you have to do rosdep and nothing happens.

We've also enabled the GitHub CI to check that everything is working correctly.

Thank you very much for everything, I proceed to close the issue
