### ISSUE TITLE
ros2 launch tiago_moveit_config moveit_rviz.launch.py

### ISSUE THREAD

**Issue by kavikode** [Tiago-Harmonic/tiago_harmonic#7]
After running
Terminal 1: ros2 launch tiago_gazebo tiago_gazebo.launch.py moveit:=True is_public_sim:=True world_name:=empty 

Terminal 2: ros2 launch tiago_moveit_config moveit_rviz.launch.py

I was able to move the arm joints in RViz2.

However, plan and executed failed. Sample output is below:
Constructing new MoveGroup connection for group 'arm' in namespace ''
[rviz2-1] [INFO] [1728613778.586191247] [moveit_4120919383.moveit.ros.move_group_interface]: Ready to take commands for planning group arm.
[rviz2-1] [INFO] [1728613781.688273087] [interactive_marker_display_96415867168800]: Sending request for interactive markers
[rviz2-1] [INFO] [1728613785.333432654] [interactive_marker_display_96415867168800]: Service response received for initialization
[rviz2-1] [INFO] [1728613815.087184444] [moveit_4120919383.moveit.ros.move_group_interface]: Plan and Execute request accepted
[rviz2-1] [ERROR] [1728613815.094067298] [rviz.rclcpp_action]: unknown goal response, ignoring...
[rviz2-1] [INFO] [1728613816.315791988] [moveit_4120919383.moveit.ros.move_group_interface]: Plan and Execute request aborted
[rviz2-1] [ERROR] [1728613816.315956231] [moveit_4120919383.moveit.ros.move_group_interface]: MoveGroupInterface::move() failed or timeout reached
[rviz2-1] [ERROR] [1728613816.322818451] [rviz.rclcpp_action]: unknown result response, ignoring...
[rviz2-1] [WARN] [1728613816.970330027] [moveit_4120919383.moveit.ros.planning_scene_monitor]: Maybe failed to update robot state, time diff: 1728612386.673s

Any suggestions, please?

Thank you!

**Comment by Juancams** [comment]
Hello @kavikode !

Thank you very much for reporting the error. I can't tell you if this is necessary in the new versions of moveit, but it seems that it is now necessary to add limits to the accelerations, which were false and 0.

If you pull [tiago_moveit_config](https://github.com/Tiago-Harmonic/tiago_moveit_config) , the `config/joint_limits.yaml` should be updated and everything should work correctly.

I'm waiting to see if it works for you with these changes.

Greetings.

**Comment by kavikode** [comment]
Thank you so much @Juancams! 

Truly grateful, it successfully executed the plan!
