### ISSUE TITLE
ros2 launch tiago_2dnav tiago_nav_bringup.launch.py is_public_sim:=True

### ISSUE THREAD

**Issue by kavikode** [Tiago-Harmonic/tiago_harmonic#9]
Many thanks for your continued support! 

Any suggestions please for the following:

ros2 launch tiago_2dnav tiago_nav_bringup.launch.py is_public_sim:=True

in Harmonic?

I am grateful sincerely to you and your team.
@Juancams

**Comment by Juancams** [comment]
Hi again @kavikode 

I've checked and it doesn't work. The only tests I've done on navigation is by running this [bringup_launch.py](https://github.com/ros-navigation/navigation2/blob/jazzy/nav2_bringup/launch/bringup_launch.py) ​​from [navigation2](https://github.com/ros-navigation/navigation2/tree/jazzy). To use it correctly, you'll have to configure a file like this [nav2_params.yaml](https://github.com/ros-navigation/navigation2/blob/jazzy/nav2_bringup/params/nav2_params.yaml), modifying the laser topic and I don't know if any other parameters, and then run the following command:

```bash
ros2 launch nav2_bringup bringup_launch.py params_file:=<path-to-params> map:=<path-to-map>
```

Before running this it is recommended that you have mapped before using slam, although if you don't have any maps it will open rviz2 empty.

I hope that with this you will be able to navigate with tiago in the harmonic simulator while we get the tiago_2dnav package working.

Greetings.

**Comment by Juancams** [comment]
Hello @kavikode 

I think it's up and running now. To get it working,  create a new repository and follow the steps in the readme.

To launch it, use the following commands:

```bash
ros2 launch tiago_gazebo tiago_gazebo.launch.py is_public_sim:=True world_name:=house
ros2 launch tiago_2dnav tiago_nav_bringup.launch.py is_public_sim:=True world_name:=small_house
```

The map doesn't match completely, but you can navigate. I'm planning to try slam and upload a map for the house.

Please tell me if this worked for you.

**Comment by kavikode** [comment]
Yes, thank you @Juancams it loads well.

I just can't seem to click on all goal position for navigation to reach in the map.

How can we make Nav 2 work?

I greatly appreciate your efforts.

**Comment by Juancams** [comment]
Sorry, you'll have to be more specific with your problem in order to resolve it. Could you send me a video of what you're trying to do?

**Comment by kavikode** [comment]
the robot does not move

**Comment by Juancams** [comment]
I need you to send me a video of what you are trying to prove, so I can help you better.

**Comment by Juancams** [comment]
Hi!

I'm going to close this issue, assuming that the bug is now fixed. In case it keeps happening, please update all repositories following the steps found in the [README.md](https://github.com/Tiago-Harmonic/tiago_harmonic/blob/jazzy/README.md), and if that doesn't fix it, please reopen the issue.

Regards.
